version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./infra/mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  php:
    build: ./infra/php
    volumes:
      - ./html:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
volumes:
  mysql:
